// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtojfoumstpmqswrtuas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0b2pmb3Vtc3RwbXFzd3J0dWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MjA3OTksImV4cCI6MjA3NzE5Njc5OX0.QBgZdyK9kKoutMcNMQ_p3MPAMD97vVVznps49AIHZR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});